name: Feature Request
description: Suggest a new feature or enhancement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Please describe the feature you would like to see.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short summary of the feature
      placeholder: e.g. Add dark mode support
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important?
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Describe the feature in detail
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Are there any alternative solutions?
    validations:
      required: false
