name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build Backend
        run: dotnet build API/API.csproj --configuration Release
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Frontend Dependencies
        run: cd client && npm install
      - name: Build Frontend
        run: cd client && npm run build
      - name: Run Backend Tests
        run: dotnet test API/API.csproj
      - name: Run Frontend Tests
        run: cd client && npm test -- --watchAll=false
